# Generated by Django 3.1.2 on 2020-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryview', '0002_auto_20201130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
