# Generated by Django 3.1.2 on 2020-12-01 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleryview', '0004_remove_list_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AddField(
            model_name='list',
            name='author',
            field=models.ForeignKey(default='Ricky', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='list',
            index_together=set(),
        ),
    ]
