# Generated by Django 3.1.2 on 2020-12-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryview', '0007_auto_20201201_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='author',
        ),
    ]
